### ISSUE TITLE
Traceback (most recent call last) "error

### ISSUE THREAD

**Issue by CursedPop** [LuisEnMarroquin/python-keylogger#1]
![error](https://user-images.githubusercontent.com/79946591/110865448-a11f8b80-8291-11eb-84f0-3f077b54caf6.PNG)

**Comment by LuisEnMarroquin** [comment]
Sorry, forgot to answer, I'll retake this project on weekend and take a look

**Comment by iGetUploaded** [comment]
This was my old account I forgot the password too so I made this one

**Comment by LuisEnMarroquin** [comment]
Hi there, I made the project a lot simpler in commit 3b243e9

Let me know if you have any issue
