### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by iGetUploaded** [LuisEnMarroquin/python-keylogger#2]
I noticed it says change the URL now does that mean it can be any URL or a specific one?

**Comment by LuisEnMarroquin** [comment]
Any url that allows you to send the keys that were logged

**Comment by iGetUploaded** [comment]
Just making sure but you change it here? 
![image](https://user-images.githubusercontent.com/54633753/146501089-d4007e2e-039a-4183-9f65-2b756d3f7222.png)

**Comment by LuisEnMarroquin** [comment]
Yes, I should probably document that better. Feel free to reopen if you have an issue
